
services:
  app:
    build:
      context: .
      args:
        BUILDPLATFORM: linux/amd64
    platform: linux/amd64
    ports:
      - "8007:8007"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - .:/app
      - /app/node_modules